%% Genera la tabla de pruebas de hipotesis con los datos arreglados
close all
clear all
clc
disp('Haciendo una tablita con parámetros y pruebas de hipótesis');

%% Información para leer los datos

heliostatos = load('../campos_info/posiciones_grande.txt', '-ascii'); 
archivo = '../data_gen/errores/errores_';
desviaciones_nominales = [0.5e-3, 0.5e-3, 0.5e-3, 0.5e-3, 0; ...
                          1.5e-3, 1.5e-3, 1.5e-3, 1.5e-3, 0; ...
                          2.5e-3, 2.5e-3, 2.5e-3, 2.5e-3, 0; ...
                          5e-3,     5e-3,   5e-3,   5e-3, 0; ...
                          1e-3,        0,      0,      0, 0; ...
                          3e-3,        0,      0,      0, 0; ...
                          5e-3,        0,      0,      0, 0; ...
                         10e-3,        0,      0,      0, 0; ...
                             0,     1e-3,      0,      0, 0; ...
                             0,     3e-3,      0,      0, 0; ...
                             0,     5e-3,      0,      0, 0; ...
                             0,    10e-3,      0,      0, 0; ...
                             0,        0,   1e-3,      0, 0; ...
                             0,        0,   3e-3,      0, 0; ...
                             0,        0,   5e-3,      0, 0; ...
                             0,        0,  10e-3,      0, 0; ...
                             0,        0,      0,   1e-3, 0; ...
                             0,        0,      0,   3e-3, 0; ...
                             0,        0,      0,   5e-3, 0; ...
                             0,        0,      0,  10e-3, 0];

% desviaciones_nominales = [...
%                           %   0,        0,      0,   1e-3, 0; ...
%                           %   0,        0,      0,   3e-3, 0; ...
%                              0,        0,      0,   5e-3, 0; ...
%                              0,        0,      0,  10e-3, 0];
                         
                         
%% Información sobre las pruebas de hipotesis
repeticiones = 100;
muestras = 1000;

%% Ciclo para generar la tabla
tablita = [];
tablitaC = [];

for d = 1:size(desviaciones_nominales, 1)
    
    % Cargando datos
    des_str = sprintf('_%1.2f', desviaciones_nominales(d, :) * 1e3);
    E = [];
    EC = [];
    load([archivo, des_str, '.mat']);
    
    % Pruebas estadísticas
    [pd_w, pd_r, pd_g, p, h] = pruebas_hipotesis(E, muestras, repeticiones);
    [pd_wC, pd_rC, pd_gC, pC, hC] = pruebas_hipotesis(EC, muestras, repeticiones);
    
    % Hace la tablita
    tablita = [tablita; ...
               [desviaciones_nominales(d, :), p, h]];

    tablitaC = [tablitaC; ...
               [desviaciones_nominales(d, :), pC, h]];
end


                         
